openapi: "3.0.3"
info:
  title: "Chat API"
  description: "Chat API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /messages:
    get:
      description: "Retrieve all messages"
      responses:
        "200":
          description: "List of all messages"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Message"
    post:
      description: "Send a new message"
      requestBody:
        description: "Message data"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        "201":
          description: "Message successfully created"
        "400":
          description: "Invalid message data"
components:
  schemas:
    Message:
      type: "object"
      properties:
        id:
          type: "string"
        sender:
          type: "string"
        message:
          type: "string"
        timestamp:
          type: "integer"
          format: "int64"
        fileUrl:
          type: "string"
          nullable: true
